title = "Hayden's Blog"
baseURL = "https://jhquilty99.github.io/blog/"
languageCode = "en-us"
theme = "ananke"
themesDir = "themes"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 12 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "G-0EZM79MMWQ"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.6
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/jhquilty99 "
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/johnhquilty/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/traffic.jpg"
  recent_posts_number = 5
